# Stage 1: React App Builder
FROM node:18.16.1-slim as react-builder

WORKDIR /app

COPY . .

RUN yarn config set workspaces-experimental true

RUN yarn install

ENV PUBLIC_URL=/swasth/

RUN yarn run build

# Stage 2: Production
FROM nginx:1.27.0-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=react-builder /app/platform/app/dist /usr/share/nginx/html

EXPOSE 8080

ENTRYPOINT ["nginx", "-g", "daemon off;"]
